bulldog_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 15

bulldog_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['front_left_wheel_joint', 'rear_left_wheel_joint']
  right_wheel: ['front_right_wheel_joint', 'rear_right_wheel_joint']
  publish_rate: 15
  pose_covariance_diagonal: [0.1, 0.1, 0.001, 0.001, 0.001, 0.05]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.05]
  cmd_vel_timeout: 0.25

  base_frame_id: base_link
  enable_odom_tf: true
  estimate_velocity_from_position: false

  wheel_separation: 0.58
  wheel_radius: 0.1706
  wheel_separation_multiplier: 1.9
  wheel_radius_multiplier: 1.0 

  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.5
      has_acceleration_limits: true
      max_acceleration       : 1.5
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.5  
      has_acceleration_limits: true
      max_acceleration       : 1.5   
