pub_rate: 1.0 
base_path: ''
analyzers:
  bulldog:
    type: diagnostic_aggregator/GenericAnalyzer
    path: 'Bulldog'
    remove_prefix: 'bulldog_driver: '
    timeout: 5.0
    contains: ['Robot Status', 'Battery Status', 'Motor Status', 'Controller Status']

